/**
 * MCP Resources: Collection schema field guides.
 * These are exposed as read-only context so the LLM knows exact field paths
 * and types before querying, eliminating guesswork and hallucinated fields.
 */

export interface CollectionFieldGuide {
  collection: string;
  description: string;
  key_fields: Record<string, string>;
  common_filters: Record<string, string>;
  notes?: string[];
}

export const COLLECTION_SCHEMAS: Record<string, CollectionFieldGuide> = {
  orders: {
    collection: "orders",
    description:
      "Food delivery orders — the core collection. Each document tracks the full lifecycle of an order from creation to delivery/cancellation.",
    key_fields: {
      _id: "ObjectId — unique order document ID",
      order_id: "String — human-readable order identifier",
      status: "Number — order status code (see status-codes resource)",
      user_id: "ObjectId — ref to users collection",
      "user.username": "String — customer first name",
      "user.last_name": "String — customer last name",
      "user.email": "String — customer email",
      "user.phone.code": "String — phone country code",
      "user.phone.number": "String — phone number",
      "user.address.country_code": "String — e.g. DZ, MA, TN",
      restaurant_id: "ObjectId — ref to restaurant collection",
      "restaurant.restaurantname": "String — restaurant display name",
      "restaurant.main_city": "String — restaurant city",
      "restaurant.store_type": "String — restaurant, dark_store, or store",
      driver_id: "ObjectId — ref to drivers collection (after acceptance)",
      "driver.username": "String — driver first name",
      "driver.phone.code": "String",
      "driver.phone.number": "String",
      main_city: "String — city name for this order",
      sub_city: "String — sub-city / zone",
      country_code: "String — DZ, MA, TN, FR, SN, ZA, etc.",
      "billings.amount.total": "Number — food total",
      "billings.amount.grand_total": "Number — final total incl fees",
      "billings.amount.delivery_amount": "Number — delivery fee",
      "billings.amount.service_charge": "Number — service charge",
      "billings.amount.coupon_discount": "Number",
      "billings.amount.offer_discount": "Number",
      "billings.amount.wallet_usage": "Number",
      "billings.epay.method": "String — payment method (CASH, CIB, etc.)",
      "billings.epay.status.current": "String — payment status",
      payment_type: "String — CASH, EPAY, etc.",
      coupon_code: "String — applied coupon code",
      "foods[]": "Array — ordered food items",
      "foods[].name": "String — food item name",
      "foods[].price": "Number — item price",
      "foods[].quantity": "Number — quantity ordered",
      "order_history.order_time": "Date — when order was placed",
      "order_history.restaurant_accepted": "Date",
      "order_history.driver_accepted": "Date",
      "order_history.driver_pickedup": "Date",
      "order_history.driver_at_restaurant": "Date",
      "order_history.driver_at_client": "Date",
      "order_history.food_delivered": "Date",
      "order_history.restaurant_rejected": "Date",
      cancelled_role: "Number — 1=admin, 2=subadmin cancelled",
      cancellation_comment: "String",
      pickup_distance: "Number — km from driver to restaurant",
      deliver_distance: "Number — km from restaurant to customer",
      is_scheduled: "Boolean — scheduled order flag",
      auto_dispatch: "Boolean — was auto-dispatched",
      source: "String — webapp or mobileapp",
      app_version: "String — STANDALONE_APP or SUPER_APP",
      createdAt: "Date — document creation timestamp",
      updatedAt: "Date — last update timestamp",
    },
    common_filters: {
      "active orders": "{ status: { $in: [1,3,5,6,17] } }",
      "delivered orders": "{ status: 7 }",
      "cancelled orders": "{ status: { $in: [9,10,90] } }",
      "by country": '{ country_code: "DZ" }',
      "by city": '{ main_city: "Algiers" }',
      "by date range":
        '{ createdAt: { $gte: ISODate("2024-01-01"), $lt: ISODate("2024-01-02") } }',
      "by user phone": '{ "user.phone.number": "666666666" }',
      "by restaurant name": '{ "restaurant.restaurantname": /pizza/i }',
    },
    notes: [
      "Status codes: 1=new, 3=accepted, 5=driver_accepted, 6=picked_up, 7=delivered, 9=cancelled_by_admin, 10=cancelled_by_user, 17=driver_at_restaurant, 90=cancelled_by_system",
      "The 'user', 'restaurant', and 'driver' objects are embedded snapshots — not live references",
      "Use createdAt for time-based queries, NOT order_history.order_time (which may be null)",
    ],
  },

  users: {
    collection: "users",
    description:
      "Customer/user accounts. Stores personal info, credentials, location, and activity logs.",
    key_fields: {
      _id: "ObjectId — unique user ID",
      email: "String — lowercase, indexed",
      username: "String — first name / display name",
      last_name: "String",
      first_name: "String",
      full_name: "String",
      "phone.code": "String — country code e.g. +213",
      "phone.number": "String — local phone number",
      full_phone: "String — complete phone (code+number), unique indexed",
      yassir_id: "String — Yassir super-app user ID",
      role: "String — e.g. customer",
      status: "Number — 1=active, 0=inactive",
      "address.fulladres": "String — primary address",
      "address.lat": "Number",
      "address.lng": "Number",
      "location.lat": "Number — last known latitude",
      "location.lng": "Number — last known longitude",
      orderCount: "Number — total orders placed",
      avg_ratings: "Number — average rating given",
      "device_info.device_type": "String — ios or android",
      "device_info.device_token": "String — push notification token",
      wallet_id: "ObjectId — ref to wallet",
      referal_code: "String — user's referral code",
      birthday: "Date",
      gender: "String",
      createdAt: "Date",
      updatedAt: "Date",
    },
    common_filters: {
      "by phone": '{ "phone.number": "666666666" }',
      "by full phone": '{ full_phone: "+213666666666" }',
      "by email": '{ email: "user@example.com" }',
      "by name (partial)": '{ username: { $regex: "eslam", $options: "i" } }',
      "active users": "{ status: 1 }",
    },
  },

  drivers: {
    collection: "drivers",
    description:
      "Delivery drivers/couriers. Contains profile, status, location, vehicle info, and performance stats.",
    key_fields: {
      _id: "ObjectId — unique driver ID",
      username: "String — first name (trimmed)",
      last_name: "String",
      first_name: "String",
      email: "String — lowercase",
      "phone.code": "String — country code",
      "phone.number": "String — local phone number",
      main_city: "String — primary operating city",
      category: "String — driver category",
      status: "Number — 1=active, 0=inactive",
      new_driver_status: "Number — onboarding status",
      currentStatus: "Number — 0=offline, 1=online, 2=busy",
      currentJob: "Number — current active deliveries count",
      avail: "Number — 1=available, 0=unavailable",
      "location.lat": "Number — current latitude",
      "location.lng": "Number — current longitude",
      "address.country_code": "String — e.g. DZ",
      "address.city": "String",
      avg_ratings: "Number — customer rating (0-5)",
      avg_store_ratings: "Number — store rating (0-5)",
      tot_req: "Number — total requests received",
      cancelled: "Number — total cancelled orders",
      deliverd: "Number — total delivered orders",
      avg_delivery: "Number — average delivery time",
      isReceiving: "Boolean — currently receiving dispatch offers",
      total_active_time: "Number — total active time",
      "currentOrders.onGoingOrdersCount": "Number",
      "currentOrders.pickedUpOrdersCount": "Number",
      driver_type: "ObjectId — ref to driver_type",
      driver_store_type: "Array<String> — types of stores they serve",
      vehicle_brand: "String",
      vehicle_model: "String",
      vehicle_registration_number: "String",
      training_date: "Date",
      date_of_birth: "Date",
      "activity.last_login": "Date",
      "activity.last_online": "Date",
      "activity.last_offline": "Date",
      createdAt: "Date",
      updatedAt: "Date",
    },
    common_filters: {
      "online drivers": "{ currentStatus: 1 }",
      "busy drivers": "{ currentStatus: 2 }",
      "offline drivers": "{ currentStatus: 0 }",
      "by city": '{ main_city: "Algiers" }',
      "by country": '{ "address.country_code": "DZ" }',
      "by name": '{ username: { $regex: "ahmed", $options: "i" } }',
    },
    notes: [
      "Collection name is 'drivers' (with s), NOT 'driver'",
      "currentStatus: 0=offline, 1=online, 2=busy",
      "avail is the legacy availability field",
    ],
  },

  restaurant: {
    collection: "restaurant",
    description:
      "Restaurants, dark stores, and stores. Contains operational, financial, and descriptive data.",
    key_fields: {
      _id: "ObjectId — unique restaurant ID",
      restaurantname: "String — display name",
      restaurant_name_i18n: "Object — i18n name translations",
      username: "String — login username",
      email: "String — unique, lowercase",
      "phone.code": "String",
      "phone.number": "String",
      main_city: "String — primary city",
      sub_city: "String — sub-city / locality",
      city_id: "ObjectId — ref to city",
      "address.fulladres": "String — full address",
      "address.lat": "Number",
      "address.lng": "Number",
      "address.country_code": "String — e.g. DZ",
      availability: "Number — 0=unavailable, 1=available",
      status: "Number — 1=active, 0=inactive",
      store_type: "String — restaurant, dark_store, store",
      avg_ratings: "Number — 0 to 5 (default 5)",
      food_count: "Number — total menu items",
      com_type: "String — commission type (common or unique)",
      "unique_commission.admin_commission": "Number — custom commission %",
      efp_time: "Number — estimated food prep time (from)",
      efp_time2: "Number — estimated food prep time (to)",
      minimum_cart: "Number — minimum order value",
      search_radius: "Number — delivery radius km (default 20)",
      priority: "Number — listing priority",
      "package_charge.package_status": "String — enabled/disabled",
      "package_charge.package_amount": "Number",
      tot_req: "Number — total order requests",
      cancelled: "Number — total cancelled",
      deliverd: "Number — total delivered",
      isPickup: "Boolean — supports pickup",
      accept_schedule_order: "Boolean — accepts scheduled orders",
      is_partner: "Boolean — special partner flag",
      "restaurantAvailability.isBusy": "Boolean — currently busy",
      "restaurantAvailability.busyUntil": "Date — busy until timestamp",
      is_third_party_integration: "Boolean",
      external_id: "String — third-party system ID",
      parent: "ObjectId — parent restaurant (franchise)",
      isMainRest: "Boolean — main restaurant in chain",
      createdAt: "Date",
      updatedAt: "Date",
    },
    common_filters: {
      "active restaurants": "{ status: 1, availability: 1 }",
      "by city": '{ main_city: "Algiers" }',
      "by country": '{ "address.country_code": "DZ" }',
      "by name": '{ restaurantname: { $regex: "pizza", $options: "i" } }',
      "busy now": '{ "restaurantAvailability.isBusy": true }',
      "dark stores only": '{ store_type: "dark_store" }',
    },
    notes: [
      "Collection name is 'restaurant' (singular), NOT 'restaurants'",
      "availability=1 means accepting orders; status=1 means account is active",
    ],
  },

  countrycurrency: {
    collection: "countrycurrency",
    description:
      "Country-level configurations: currency, feature flags, operational settings. One document per country.",
    key_fields: {
      _id: "ObjectId",
      "country.code":
        "String — ISO country code (DZ, MA, TN, FR, SN, ZA) — UNIQUE",
      "country.name": "String — country name",
      "country.currency_code": "String — e.g. DZD, MAD, TND, XOF",
      "country.currency_symbol": "String — e.g. د.ج, DH, DT",
      "country.timeZone": "String — e.g. Africa/Algiers",
      "country.time_zone": "String — alternate timezone field",
      "country.isOrderDispatch": "Boolean — dispatch enabled",
      "country.sameZoneOnly": "Boolean — restrict to same zone",
      "country.service_charge": "Number — default service charge",
      "country.has_tipping_feature": "Boolean",
      "country.tip_percentage_limit": "Number",
      "country.cancel_window_time": "Number — minutes",
      "country.activate_wallet": "Boolean",
      "country.enable_bonus_management": "Boolean",
      "country.enableCourierEpayMethod": "Boolean",
      "country.enableBusyRestaurantSettings": "Boolean",
      "country.enable_shift_planning": "Boolean",
      "country.enable_driver_adjustments": "Boolean",
      "country.at_restaurant_time_flag": "Number — minutes (default 5)",
      "country.drop_off_time_flag": "Number — minutes (default 5)",
      "country.vat_restaurant.flag": "Boolean — VAT enabled",
      "country.vat_restaurant.value": "Number — VAT percentage",
      "country.schedule_order.cutoff_time": "Number",
      "country.schedule_order.days_ahead": "Number",
      status: "Number — 1=active",
    },
    common_filters: {
      "Algeria config": '{ "country.code": "DZ" }',
      "Morocco config": '{ "country.code": "MA" }',
      "all active": "{ status: 1 }",
      "currency for country":
        '{ "country.code": "DZ" } → read country.currency_code',
    },
    notes: [
      "IMPORTANT: Filter by 'country.code' NOT 'country_code'. The country field is a nested object.",
      "Each document represents one country with all its feature flags",
    ],
  },

  city: {
    collection: "city",
    description:
      "City-level operational configurations: dispatch settings, driver radius, working hours, fare settings.",
    key_fields: {
      _id: "ObjectId",
      cityname: "String — area/zone name (legacy, use state for city search)",
      state: "String — actual city name (used in search)",
      country_code: "String — DZ, MA, TN, etc.",
      status: "Number — 1=active",
      auto_dispatch: "Boolean — auto-dispatch enabled",
      auto_dispatch_algorithm: "String — normal, yassir_dispatch_v2, next_mv",
      max_orders: "Number — max concurrent orders per driver",
      max_proc_orders: "Number — max processing orders",
      max_picked_orders: "Number — max picked up orders",
      max_dispatch_time: "Number — max minutes to try dispatching",
      max_rejected_drivers: "Number — max rejections before fail",
      dispatch_delay_time: "Number — delay minutes before dispatch starts",
      driver_radius: "Number — search radius km (default 20)",
      search_radius: "Number — restaurant search radius km",
      admin_commission: "Number — commission percentage",
      "location.lat": "Number",
      "location.lng": "Number",
      currency_symbol: "String",
      "timer_config.isEnabled": "Boolean",
      "timer_config.storeTimer": "Number — minutes",
      "timer_config.darkstoreTimer": "Number — minutes",
      "timer_config.restaurantTimer": "Number — minutes",
      busySettings: "Boolean — busy settings enabled",
      maxRejectedOrders: "Number",
      busyTime: "Number — busy duration",
      aging: "Boolean — aging enabled",
      aging_time_min: "Number — aging minutes",
      batching: "Boolean — order batching enabled",
      "fraud_management_settings.status": "Boolean",
      "working_hours.monday.start_time": "Number — timestamp",
      "working_hours.monday.end_time": "Number — timestamp",
    },
    common_filters: {
      "by country": '{ country_code: "DZ" }',
      "auto-dispatch cities": "{ auto_dispatch: true }",
      "active cities": "{ status: 1 }",
    },
    notes: [
      "Use 'state' field for city name searches, NOT 'cityname' (which is the zone/area name)",
    ],
  },

  cartv2: {
    collection: "cartv2",
    description:
      "Active shopping carts (v2). Each document is a user's current cart for a specific restaurant.",
    key_fields: {
      _id: "ObjectId",
      user_id: "ObjectId — ref to users (indexed)",
      restaurant_id: "ObjectId — ref to restaurant (indexed)",
      status: "String — CREATED, ORDER, etc.",
      order_id: "String — linked order ID (after checkout)",
      country_code: "String",
      currency_code: "String",
      currency_symbol: "String",
      "cart_details[]": "Array — items in cart",
      "cart_details[].id": "ObjectId — food item ref",
      "cart_details[].quantity": "Number",
      "cart_details[].price": "Number",
      "cart_details[].instruction": "String",
      "cart_details[].has_offer": "Boolean",
      "cart_details[].offer_discount": "Number",
      sub_total: "Number — subtotal before discounts",
      total_before_coupon: "Number",
      total_after_coupon: "Number",
      total_ttc: "Number — total including tax",
      total_tax: "Number",
      delivery_charge: "Number",
      service_charge: "Number",
      coupon_code: "String",
      coupon_discount: "Number",
      discount_amount: "Number",
      offer_type: "String — NONE, DISCOUNT, COUPON, OFFER ITEM",
      payment_method: "String",
      auto_dispatch: "Boolean",
      is_pickup_order: "Boolean",
      "location.lat": "Number — delivery location",
      "location.lng": "Number",
      createdAt: "Date",
      updatedAt: "Date",
    },
    common_filters: {
      "user's active cart": '{ user_id: ObjectId("..."), status: "CREATED" }',
      "by country": '{ country_code: "DZ" }',
    },
    notes: [
      "Collection name is 'cartv2', NOT 'cart' or 'carts'",
      "status='CREATED' means active cart; status='ORDER' means converted to order",
    ],
  },

  dispatch: {
    collection: "dispatches",
    description:
      "Dispatch records — one per dispatch attempt per order. Tracks which couriers were considered and selected.",
    key_fields: {
      _id: "ObjectId",
      order_id: "String — the order this dispatch is for",
      dispatch_type: "String — auto or manual",
      mode: "String — dispatch mode",
      city: "String — city name",
      country_code: "String",
      couriers_result: "Array — list of considered drivers with scores",
      selected_courier: "Object — the driver who was selected",
      is_dispatch_shadow_enabled: "Boolean",
      createdAt: "Date",
      updatedAt: "Date",
    },
    common_filters: {
      "by order": '{ order_id: "ORD-123456" }',
      "by city": '{ city: "Algiers" }',
      "auto dispatches": '{ dispatch_type: "auto" }',
    },
  },
};

export function getSchemaResource(collectionName: string): string | null {
  const schema = COLLECTION_SCHEMAS[collectionName];
  if (!schema) return null;
  return JSON.stringify(schema, null, 2);
}

export function getAllSchemasCompact(): string {
  const compact = Object.entries(COLLECTION_SCHEMAS).map(([key, schema]) => ({
    collection: schema.collection,
    description: schema.description,
    fields: Object.keys(schema.key_fields).join(", "),
    filter_examples: schema.common_filters,
    notes: schema.notes,
  }));
  return JSON.stringify(compact, null, 2);
}
